version: '3.8'

networks:
  default:
    name: 'z1'

services: 
  db:
    image: postgres:15.4-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test:  "pg_isready -U ${DB_USER}"
      interval: 1s
      timeout: 5s
      retries: 5
    depends_on:
      redis:
        condition: service_started
  redis:
    image: 'redis:alpine'
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s