networks:
  default:
    name: 'z1'

services:
  app: 
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - ${PORT}:${PORT}
    command: yarn start:dev
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
      db:
        condition: service_healthy
  db:
    image: postgres:15.4-alpine
    container_name: db
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:5432
    healthcheck:
      test:  "pg_isready -U ${DB_USER}"
      interval: 1s
      timeout: 5s
      retries: 5
  redis:
    image: 'redis:alpine'
    ports:
      - ${REDIS_PORT}:6379
    healthcheck:
      test:
        - CMD
        - redis-cli
        - ping
      retries: 3
      timeout: 5s